version: '3.1'
services:
  mysql:
    image: "mysql:8"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "rootPassword"
      MYSQL_DATABASE: "website"
      MYSQL_USER: "website"
      MYSQL_PASSWORD: "password"
    command: ["--max_allowed_packet=512M", "--innodb_log_file_size=400M"]
    restart: always
    ports:
      - "3307:3306"
volumes:
  mysql_data:
    driver: local
