spring:
  datasource:
    url: jdbc:mysql://localhost:3307/website?useSSL=true&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: website
    password: password
    initialization-mode: never

  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
